# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oIOJz5jHId6nq17tpL75C07l6aBvf5PZ
"""

import streamlit as st

st.title('Hola mundo')